name: Build and Push Container Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GenerateTag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ECR_ROLE_ASSUME}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build \
          --build-arg APPLICATION_ID=${{ vars.APPLICATION_ID }} \
          -t $REGISTRY/${{secrets.ECR_REPOSITORY}}:$TAG .

          
          docker tag $REGISTRY/${{secrets.ECR_REPOSITORY}}:$TAG $REGISTRY/${{secrets.ECR_REPOSITORY}}:latest
          
          docker push --all-tags $REGISTRY/${{secrets.ECR_REPOSITORY}}